baseURL = 'https://example.org/'
locale = 'en-US'
title = 'Site Title'

[pagination]
  pagerSize = 10

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'

[params]
  summaryMaxLength = 300

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = true